"use strict";
exports.__esModule = true;
exports.ANKI_CONNECT_ADDNOTES = exports.ANKI_CONNECT_NOTESINFO = exports.ANKI_CONNECT_FINDNOTES = exports.ANKI_CONNECT_VERSION = exports.ANKI_MODEL_FOR_CLOZE_TAG = exports.ANKI_DECK_FOR_CLOZE_TAG = exports.config = void 0;
exports.config = require("./config");
exports.ANKI_DECK_FOR_CLOZE_TAG = "Max Infinity";
exports.ANKI_MODEL_FOR_CLOZE_TAG = "Chinese";
exports.ANKI_CONNECT_VERSION = 6;
exports.ANKI_CONNECT_FINDNOTES = "findNotes";
exports.ANKI_CONNECT_NOTESINFO = "notesInfo";
exports.ANKI_CONNECT_ADDNOTES = "addNotes";
